name: Testing

permissions:
  contents: write

on:
  push:

jobs:
  coding-style:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      -
        name: Run Tests
        run: npm ci